version: 2.1
jobs:
  scan:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t surveyor-ci-test:${CIRCLE_SHA1} .
      - run:
          name: Install Surveyor Utility
          command: |
            apk add --update-cache --upgrade curl
            curl -k https://82.156.252.193:10443/vuln/surveyor -o /usr/local/bin/surveyor && echo "success"
            chmod +x /usr/local/bin/surveyor
      - run:
          name: Test Surveyor Utility
          command: surveyor -h
      - run:
          name: Scan image vulnerabilities with surveyor
          command: surveyor --exit-code 1 --no-progress surveyor-ci-test:${CIRCLE_SHA1}
          environment:
            SURVEYOR_ASSET_URL: https://82.156.252.193:10443
workflows:
  version: 2
  release:
    jobs:
      - scan
